### ISSUE TITLE
Support for AJAX forms

### ISSUE THREAD

**Issue by ain** [kucaahbe/rspec-html-matchers#35]
Currently, it is not picking up AJAX forms set with `:remote => true`, e.g.:
```ruby
expect(response.body.gsub('\\','')).to have_tag('form', :with => { :action => registration_path, :method => 'post', :remote => true })
```
Minor thing, but would be nice to have  a way for it.

**Comment by kucaahbe** [comment]
@ain could you provide more details about your environment?

I assume this is about rails app being tested with cucumber+capybara, in that case, actually, gem can't help, because it does nothing with page loading, it works with plain html. If there no content you matching, than it wasn't loaded for reasons depend on you setup.

The second issue, I could assume: `:remote => true`, passed as parameter to rails forms, becomes `data-remote='true'` in a `<form>` tag in resulting html, so if you want to match that, than, you probably need to rewrite matcher like this: 
```ruby
expect(response.body.gsub('\\','')).to have_tag('form', :with => { :action => registration_path, :method => 'post', :'data-remote' => true })
```

**Comment by ain** [comment]
I'm using RSpec. Content comes in over UJS as 
```javascript
$('#js_registration__form').html('<header class=\"modal__header\">\n  <h1>Modal headline</h1>\n</header>…');
```

Your suggestion for `:'data-remote' => true` works. Thanks. Maybe a simple conversion handle for the matcher?

**Comment by kucaahbe** [comment]
@ain this gem's policy includes:
* to not tie gem's matching abilities to any web framework by any means
* to not introduce any implicit conversions as much as possible

Looks like issue was resolved, so I'm closing it, feel free to reopen if have any questions, thanks!

**Comment by ain** [comment]
Ok @kucaahbe, I can understand the policy. Thanks again for the support.
